######################## Mesh Generation function with GMSH ####################
function MeshGenerator(L,H,L_d,H_d,r_t,y_t,d_pml,l_0,l_d,l_pml)
    gmsh.initialize()
    gmsh.option.setNumber("General.Terminal", 1)
    gmsh.option.setNumber("Mesh.Algorithm", 6)
    gmsh.clear()
    gmsh.model.add("t2") # name it whatever you want

    # Add points
    gmsh.model.geo.addPoint(-L/2, -H/2, 0, l_0, 1)
    gmsh.model.geo.addPoint( L/2, -H/2, 0, l_0, 2)
    gmsh.model.geo.addPoint( L/2,  H/2, 0, l_0, 3)
    gmsh.model.geo.addPoint(-L/2,  H/2, 0, l_0, 4)
    gmsh.model.geo.addPoint(-L/2, -H/2-d_pml, 0, l_pml, 5)
    gmsh.model.geo.addPoint( L/2, -H/2-d_pml, 0, l_pml, 6)
    gmsh.model.geo.addPoint( L/2,  H/2+d_pml, 0, l_pml, 7)
    gmsh.model.geo.addPoint(-L/2,  H/2+d_pml, 0, l_pml, 8)
    gmsh.model.geo.addPoint(-L/2-d_pml, -H/2, 0, l_pml, 9)
    gmsh.model.geo.addPoint( L/2+d_pml, -H/2, 0, l_pml, 10)
    gmsh.model.geo.addPoint( L/2+d_pml,  H/2, 0, l_pml, 11)
    gmsh.model.geo.addPoint(-L/2-d_pml,  H/2, 0, l_pml, 12)
    gmsh.model.geo.addPoint(-L/2-d_pml, -H/2-d_pml, 0, l_pml, 13)
    gmsh.model.geo.addPoint( L/2+d_pml, -H/2-d_pml, 0, l_pml, 14)
    gmsh.model.geo.addPoint( L/2+d_pml,  H/2+d_pml, 0, l_pml, 15)
    gmsh.model.geo.addPoint(-L/2-d_pml,  H/2+d_pml, 0, l_pml, 16)
    gmsh.model.geo.addPoint(-L_d/2, -H_d/2, 0, l_d, 17)
    gmsh.model.geo.addPoint( L_d/2, -H_d/2, 0, l_d, 18)
    gmsh.model.geo.addPoint( L_d/2,  H_d/2, 0, l_d, 19)
    gmsh.model.geo.addPoint(-L_d/2,  H_d/2, 0, l_d, 20)
    gmsh.model.geo.addPoint(-r_t, y_t  , 0, l_d, 21)
    gmsh.model.geo.addPoint(   0, y_t  , 0, l_d, 22)
    gmsh.model.geo.addPoint( r_t, y_t  , 0, l_d, 23)
    #gmsh.model.geo.addPoint(x_s,y_s, 0, l_s, 17)
    # Add lines
    gmsh.model.geo.addLine(  1,  2,  1)
    gmsh.model.geo.addLine(  2,  3,  2)
    gmsh.model.geo.addLine(  3,  4,  3)
    gmsh.model.geo.addLine(  4,  1,  4)
    gmsh.model.geo.addLine(  5,  6,  5)
    gmsh.model.geo.addLine( 10, 11,  6)
    gmsh.model.geo.addLine(  7,  8,  7)
    gmsh.model.geo.addLine( 12,  9,  8)
    gmsh.model.geo.addLine( 13,  5,  9)
    gmsh.model.geo.addLine(  5,  1,  10)
    gmsh.model.geo.addLine(  1,  9,  11)
    gmsh.model.geo.addLine(  9, 13,  12)
    gmsh.model.geo.addLine(  6, 14,  13)
    gmsh.model.geo.addLine( 14, 10,  14)
    gmsh.model.geo.addLine( 10,  2,  15)
    gmsh.model.geo.addLine(  2,  6,  16)
    gmsh.model.geo.addLine(  3, 11,  17)
    gmsh.model.geo.addLine( 11, 15,  18)
    gmsh.model.geo.addLine( 15,  7,  19)
    gmsh.model.geo.addLine(  7,  3,  20)
    gmsh.model.geo.addLine( 12,  4,  21)
    gmsh.model.geo.addLine(  4,  8,  22)
    gmsh.model.geo.addLine(  8, 16,  23)
    gmsh.model.geo.addLine( 16, 12,  24)
    gmsh.model.geo.addLine( 17, 18,  25)
    gmsh.model.geo.addLine( 18, 19,  26)
    gmsh.model.geo.addLine( 19, 20,  27)
    gmsh.model.geo.addLine( 20, 17,  28)
    gmsh.model.geo.addCircleArc(21, 22, 23, 29)
    gmsh.model.geo.addCircleArc(23, 22, 21, 30)
    # Construct curve loops and surfaces 
    gmsh.model.geo.addCurveLoop([1, 2, 3, 4], 1)
    gmsh.model.geo.addCurveLoop([5,-16,-1,-10], 2)
    gmsh.model.geo.addCurveLoop([-15, 6, -17, -2], 3)
    gmsh.model.geo.addCurveLoop([-3, -20, 7, -22], 4)
    gmsh.model.geo.addCurveLoop([-11, -4, -21, 8], 5)
    gmsh.model.geo.addCurveLoop([ 9, 10, 11, 12], 6)
    gmsh.model.geo.addCurveLoop([13, 14, 15, 16], 7)
    gmsh.model.geo.addCurveLoop([17, 18, 19, 20], 8)
    gmsh.model.geo.addCurveLoop([21, 22, 23, 24], 9)
    gmsh.model.geo.addCurveLoop([25, 26, 27, 28], 10)
    gmsh.model.geo.addCurveLoop([29, 30], 11)
    gmsh.model.geo.addPlaneSurface([1,10,11], 1)
    gmsh.model.geo.addPlaneSurface([2], 2)
    gmsh.model.geo.addPlaneSurface([3], 3)
    gmsh.model.geo.addPlaneSurface([4], 4)
    gmsh.model.geo.addPlaneSurface([5], 5)
    gmsh.model.geo.addPlaneSurface([6], 6)
    gmsh.model.geo.addPlaneSurface([7], 7)
    gmsh.model.geo.addPlaneSurface([8], 8)
    gmsh.model.geo.addPlaneSurface([9], 9)
    gmsh.model.geo.addPlaneSurface([10], 10)
    gmsh.model.geo.addPlaneSurface([11], 11)
    # Physical groups
    gmsh.model.addPhysicalGroup(0, [17, 18, 19, 20], 1)
    gmsh.model.setPhysicalName(0, 1, "InnerVertices")
    gmsh.model.addPhysicalGroup(0, [5,6,7,8,9,10,11,12,13,14,15,16], 2)
    gmsh.model.setPhysicalName(0, 2, "OuterVertices")
    gmsh.model.addPhysicalGroup(1, [ 7, 19, 23], 3)
    gmsh.model.setPhysicalName(1, 3, "TopSide")
    gmsh.model.addPhysicalGroup(1, [14, 6, 18], 4)
    gmsh.model.setPhysicalName(1, 4, "RightSide")
    gmsh.model.addPhysicalGroup(1, [24, 8, 12], 5)
    gmsh.model.setPhysicalName(1, 5, "LeftSide")
    gmsh.model.addPhysicalGroup(1, [ 9, 5, 13], 6)
    gmsh.model.setPhysicalName(1, 6, "BottomSide")
    gmsh.model.addPhysicalGroup(1, [25, 26, 27, 28], 7)
    gmsh.model.setPhysicalName(1, 7, "InnerSides")
    gmsh.model.addPhysicalGroup(2, [2,3,4,5,6,7,8,9], 8)
    gmsh.model.setPhysicalName(2, 8, "PML")
    gmsh.model.addPhysicalGroup(2, [1], 9)
    gmsh.model.setPhysicalName(2, 9, "Normal")
    gmsh.model.addPhysicalGroup(2, [10], 10)
    gmsh.model.setPhysicalName(2, 10, "Design")
    gmsh.model.addPhysicalGroup(2, [11], 11)
    gmsh.model.setPhysicalName(2, 11, "Target")
    gmsh.model.geo.synchronize()
    
    # Set periodic mesh on the left and right side
    #gmsh.model.mesh.setPeriodic(1, [2], [4],
    #                        [1, 0, 0, L, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1])
    # We can then generate a 2D mesh...
    gmsh.model.mesh.generate(2)
    
    # ... and save it to disk
    gmsh.write("t2.msh")
    gmsh.finalize()
end